force-app/main/default/objects/Cal_API_Base_URL__mdt/Cal_API_Base_URL__mdt.object-meta.xml
<CustomObject>
    <label>Cal API Base URL</label>
    <pluralLabel>Cal API Base URLs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cal_API_Base_URL__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cal_API_Base_URL__mdt/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <label>Base URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Cal_API_Base_URL__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>za</fullName>
                <default>true</default>
                <label>za</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalloutClass.cls
/*
@Author : Jyoti Tripathi
Description : To make the callout and get holidays
*/

public class CalloutClass {
    public static List<ResponseClassCal.Holidays> getInfoFromExternalService(String saID) {
        List<Cal_API_Base_URL__mdt> endpointDetails = Cal_API_Base_URL__mdt.getAll().values();
        List<ResponseClassCal.Holidays> holidaysOnDOB = new List<ResponseClassCal.Holidays>();
        String currentYear = String.valueof(System.Today().year());
        Integer dobMonth = Integer.valueOf(saID.mid(2, 2));
        Integer dobDay = Integer.valueOf(saID.mid(4, 2));
        String formatEndpointURL = String.format(
            '{0}{1}{2}{3}{4}{5}{6}',
            new List<String>{
                endpointDetails[0].Base_URL__c,
                '&api_key=',
                endpointDetails[0].API_Key__c,
                '&country=',
                endpointDetails[0].Country__c,
                '&year=',
                currentYear
            }
        );
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint(formatEndpointURL);
        HttpResponse res = new Http().send(req);

        // Replacing the JSON keys, as date and datetime are reserved keywords in system.
        String replaceReservedJOSN = res.getBody().replaceAll('"date"', '"Date_Z"');
        replaceReservedJOSN = replaceReservedJOSN.replaceAll('"datetime"', '"Datetime_Z"');
        ResponseClassCal obj = (ResponseClassCal) JSON.deserialize(replaceReservedJOSN, ResponseClassCal.class);

        for (ResponseClassCal.Holidays holidays : obj.Response.holidays) {
            if (
                Integer.valueOf(holidays.date_Z.Datetime_Z.year) == Integer.valueOf(currentYear) &&
                Integer.valueOf(holidays.date_Z.Datetime_Z.month) == dobMonth &&
                Integer.valueOf(holidays.date_Z.Datetime_Z.day) == dobDay
            ) {
                holidaysOnDOB.add(holidays);
            }
        }
        return holidaysOnDOB;
    }
}